name: tgt
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      # MacOS-specific dependencies
      - torch==2.6.0; sys_platform == "darwin"
      - torchvision==0.21.0; sys_platform == "darwin"
      - torchaudio==2.6.0; sys_platform == "darwin"

      # Windows-specific dependencies
      - --extra-index-url https://download.pytorch.org/whl/cu124
      - torch==2.6.0+cu124; sys_platform == "win32"
      - torchvision==0.21.0+cu124; sys_platform == "win32"
      - torchaudio==2.6.0+cu124; sys_platform == "win32"
      - cupy-cuda12x; sys_platform == "win32"

      # General pip packages
      - annotated-types
      - anyio
      - click
      - deepl
      - dotenv
      - fastapi
      - h11
      - idna
      - jinja2
      - msal
      - openai-whisper
      - openpyxl
      - pandas
      - pydantic
      - pydantic_core
      - pykakasi
      - pypinyin
      - python-multipart
      - requests
      - sacremoses
      - sniffio
      - spacy
      - spacy_stanza
      - sse_starlette
      - stanza
      - starlette
      - tqdm
      - typing-inspection
      - typing_extensions
      - uvicorn
      - wandb
      - whisperx
      - setuptools
      - cupy-cuda12x

