name: Automatic Workflow Distribution

on:
  push:
    paths:
      - "source/main.py"

jobs:
  windows-distribution:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with: 
        python-version: 3.12.3

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Download Whisper assets
      shell: bash
      run: |
        # Clone Whisper repository and copy only the assets folder
        git clone --depth 1 https://github.com/openai/whisper.git whisper-repo
        mkdir -p source/whisper
        cp -r whisper-repo/whisper/assets source/whisper/
        # Clean up the temporary clone
        rm -rf whisper-repo

    - name: Remove temp and Build binary with PyInstaller
      shell: bash
      run: |
        pyinstaller --clean --onefile \
          --add-data "../source/materials/*:materials" \
          --add-data "../source/whisper/assets/*:whisper/assets" \
          --specpath windows-distribution/ \
          --distpath windows-distribution/dist \
          --workpath windows-distribution/build \
          --name tgt_windows source/main.py

    - name: Push generated .exe to repository
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      shell: bash
      run: |
        git config --global user.name "Alejandra Camelo"
        git config --global user.email "camelo.cruz@leibniz-zas.de"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/OWNER/REPO.git
        git add windows-distribution/dist/tgt_windows.exe
        git commit -m "Add generated tgt_windows.exe binary [skip ci]"
        git push origin main
