name: Automatic Workflow Distribution

on:
  push:
    paths:
      - "source/main.py"

jobs:
  windows-distribution:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with: 
        python-version: 3.12.3

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Remove temp and Build binary with PyInstaller
      shell: bash
      run: |
        cd source
        pyinstaller --clean --onefile --add-data "materials/*:materials" --specpath windows-distribution/ --distpath windows-distribution/dist --workpath windows-distribution/build --name tgt_windows main.py

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-artifact
        path: windows-distribution/dist
