name: Automatic Workflow Distribution

on:
  push:
    paths:
      - "source/**/*.py"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Check Out Repository
      uses: actions/checkout@v3

    - name: Install GitHub CLI
      run: |
        sudo apt-get install -y gh
      
    - name: Delete old workflow runs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Fetch the workflow runs
        WORKFLOW_ID=$(gh workflow list --json name,id -q '.[] | select(.name=="Automatic Workflow Distribution") | .id')
        echo "Workflow ID: ${WORKFLOW_ID}"
        if [ -z "${WORKFLOW_ID}" ]; then
          echo "Error: Unable to find workflow ID." >&2
          exit 1
        fi
        # Delete workflow runs older than the latest one
        gh run list --workflow $WORKFLOW_ID --json databaseId -q '.[1:] | .[].databaseId' | while read -r RUN_ID; do
          echo "Deleting run ID: $RUN_ID"
          echo "y" | gh run delete "$RUN_ID"
        done
          
  windows-distribution:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with: 
        python-version: 3.12.7

    - name: Clean Numba Cache
      shell: bash
      run: |
        rm -rf ~/.cache/numba  # Remove any cached Numba files

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Remove temp and Build binary with PyInstaller
      shell: bash
      run: |
        cd source
        pyinstaller --clean --onefile \
          --add-data ../materials/*:materials \
          --add-data ../whisper/assets/*:whisper/assets \
          --specpath windows-distribution/ \
          --distpath windows-distribution/dist \
          --workpath windows-distribution/build \
          --name tgt_windows main.py
          --hidden-import numba

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-artifact
        path: source/windows-distribution/dist
