name: Automatic Workflow Distribution

on:
  push:
    paths:
      - "source/main.py"

jobs:
  windows-distribution:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with: 
        python-version: 3.12.3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Remove temp and Build binary with PyInstaller
      run: |
        cd source
        Remove-Item -Path "$env:TEMP\*" -Force -Recurse
        # Clean build and dist directories if they exist
        Remove-Item -Path "dist" -Recurse -Force
        Remove-Item -Path "build" -Recurse -Force
        pyinstaller --clean --onefile --add-data "materials/*;materials" --add-data "$(python -c 'import whisper, os; print(os.path.join(os.path.dirname(whisper.__file__), \"assets\"))')/*;whisper/assets" main.py

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-artifact
        path: dist/main.exe
