name: "Hugging Face TGT App CI/CD"

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

  pull_request:
    branches:
      - main

jobs:
  sync_to_hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.email "camelo.cruz@leibniz-zas.de"
          git config user.name "GitHub Actions"

      # Only runs if the workflow was triggered by a tag like `v1.3.0`
      - name: Check for version tag
        id: version_check
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION="${GITHUB_REF##*/}"  # Extract v1.3.0
            VERSION="${VERSION#v}"       # Remove 'v' prefix
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "No version tag detected. Skipping version update."
          fi

      - name: Update Dockerfile version (only if version was found)
        if: steps.version_check.outputs.version
        run: |
          VERSION=${{ steps.version_check.outputs.version }}
          echo "Updating Dockerfile version to $VERSION"
          sed -i "s/^LABEL version=.*/LABEL version=\"$VERSION\"/" Dockerfile
          sed -i "s/^ENV APP_VERSION=.*/ENV APP_VERSION=$VERSION/" Dockerfile

      - name: Commit and push Dockerfile version update
        if: steps.version_check.outputs.version
        run: |
          git add Dockerfile
          git commit -m "chore(docker): bump version to ${{ steps.version_check.outputs.version }}" || echo "No changes to commit"
          git push origin main

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HUGGING_KEY }}
        run: |
          git remote add hf https://camelo-cruz:${HF_TOKEN}@huggingface.co/spaces/camelo-cruz/LeibnizDream
          git push hf main
